name: 'Setup Linux Environment'
description: 'Restores caches for Linux runtime'

inputs:
  compiler:
    description: 'Compiler to use for cache key'
    required: false
    default: 'unknown'

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
