name: 'Vcpkg Cache'
description: 'sets up vcpkg to use NuGet for caching'
inputs:
  gh-token:
    description: 'GitHub Token for GHCR auth'
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps: 
    # --- WINDOWS: (dotnet nuget) ---
    - name: setup vcpkg nuget source
      if: runner.os == 'Windows'
      shell: bash
      run: |
        dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --name "GitHub" \
          --username "${{ github.repository_owner }}" \
          --password "${{ inputs.gh-token }}" \
          --store-password-in-clear-text

    # --- other: (mono + nuget.exe) ---
    - name: setup vcpkg nuget source
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # download nuget.exe
        wget -qO nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        NUGET_PATH="$(pwd)/nuget.exe"
        
        # add source
        mono "$NUGET_PATH" sources add \
          -Name "GitHub" \
          -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          -UserName "${{ github.repository_owner }}" \
          -Password "${{ inputs.gh-token }}" \
          -StorePasswordInClearText
        
        # set API key for push
        mono "$NUGET_PATH" setapikey "${{ inputs.gh-token }}" \
          -Source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"