name: 'Build Linux Container'
description: 'Builds and pushes the Linux Docker image'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: ci/docker/linux
        push: true
        load: false
        tags: |
          ghcr.io/${{ github.repository }}:linux-latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:linux-cache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:linux-cache,mode=max
