name: 'Setup Windows Environment'
description: 'Restores Vcpkg, BuildCache etc.'
inputs:
  compiler:
    description: 'Compiler suffix for cache key (msvc or clang)'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Restore BuildCache directory
      uses: actions/cache@v4
      with:
        path: ~/.buildcache
        key: buildcache-windows-${{ inputs.compiler }}-${{ github.sha }}
        restore-keys: |
          buildcache-windows-${{ inputs.compiler }}-

    - name: Setup Vcpkg Environment
      shell: pwsh
      run: |
        $vcpkgPath = $env:VCPKG_INSTALLATION_ROOT
        if (-not (Test-Path "$vcpkgPath")) {
           Write-Error "Vcpkg not found at VCPKG_INSTALLATION_ROOT ($vcpkgPath)"
           exit 1
        }
        
        Write-Host "Using Vcpkg at $vcpkgPath"
        "VCPKG_ROOT=$vcpkgPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "VCPKG_BINARY_SOURCES=clear;x-gha,readwrite" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install BuildCache
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
        Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - name: Enable GitHub Actions Cache for Vcpkg
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
