name: 'Setup Windows Environment'
description: 'Restores Vcpkg, BuildCache etc.'
inputs:
  compiler:
    description: 'compiler to CMakeUserPresets.json'
    required: true

runs:
  using: "composite"
  steps:
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Vcpkg Environment
      shell: pwsh
      run: |
        $vcpkgPath = $env:VCPKG_INSTALLATION_ROOT
        if (-not (Test-Path "$vcpkgPath")) {
           Write-Error "Vcpkg not found at VCPKG_INSTALLATION_ROOT ($vcpkgPath)"
           exit 1
        }
        "VCPKG_ROOT=$vcpkgPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    - name: Install BuildCache
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/bits-n-bites/buildcache/-/releases/v0.31.7/downloads/buildcache-windows.zip" -OutFile "buildcache.zip"
        Expand-Archive buildcache.zip -DestinationPath c:\buildcache
        echo "c:\buildcache\buildcache\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append