name: 'Build flashmini'
description: 'Handles Caching, Configuration, and Compilation'
inputs:
  cache_prefix:
    description: 'Cache Prefix e.g. OS'
    required: true
  compiler:
    description: 'Compiler'
    required: true
  backend:
    description: 'Backend'
    required: true

runs:
  using: "composite"
  steps:
    # --- 1. setup vcpkg cache ---
    - name: setup vcpkg
      uses: ./.github/actions/setup-vcpkg-cache
      
    # --- 2. configure ---
    - name: Configure CMake
      shell: bash
      run: |
        [ -f ci/CMakeUserPresets.json ] && cp ci/CMakeUserPresets.json CMakeUserPresets.json
        cmake --preset ci_${{ inputs.compiler }}_af_${{ inputs.backend }}

    # --- 4. restore BuildCache ---
    - name: Restore BuildCache
      id: buildcache
      uses: ./.github/actions/restore-cache
      with:
        path: .buildcache
        key: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}-${{ github.run_id }}
        restore-keys: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}-
        global-tag: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}

    # --- 5. build ---
    - name: Build
      shell: bash
      run: cmake --build --preset ci_${{ inputs.compiler }}_af_${{ inputs.backend }}

    # --- 6. save BuildCache ---
    - name: Save BuildCache
      if: always()
      uses: ./.github/actions/save-cache
      with:
        path: .buildcache
        key: ${{ steps.buildcache.outputs.primary-key }}
        global-tag: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}