name: 'Build flashmini'
description: 'Handles Caching, Configuration, and Compilation'
inputs:
  cache_prefix:
    description: 'Cache Prefix e.g. OS'
    required: true
  compiler:
    description: 'Compiler'
    required: true
  backend:
    description: 'Backend'
    required: true

runs:
  using: "composite"
  steps:
    # --- 1. Restore Vcpkg ---
    - name: Restore Vcpkg
      id: vcpkg
      uses: ./.github/actions/restore-cache
      with:
        path: vcpkg_installed
        key: vcpkg-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}-${{ hashFiles('vcpkg.json') }}

        global-tag: vcpkg-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}

    # --- 2. Configure ---
    - name: Configure CMake
      shell: bash
      run: |
        [ -f ci/CMakeUserPresets.json ] && cp ci/CMakeUserPresets.json CMakeUserPresets.json
        cmake --preset ci_${{ inputs.compiler }}_af_${{ inputs.backend }}

    # --- 3. Save Vcpkg ---
    - name: Save Vcpkg
      if: steps.vcpkg.outputs.cache-hit != 'true'
      uses: ./.github/actions/save-cache
      with:
        path: vcpkg_installed
        key: ${{ steps.vcpkg.outputs.primary-key }}
        global-tag: vcpkg-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}

    # --- 4. Restore BuildCache ---
    - name: Restore BuildCache
      id: buildcache
      uses: ./.github/actions/restore-cache
      with:
        path: .buildcache
        key: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}-${{ github.run_id }}
        restore-keys: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}-

        global-tag: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}

    # --- 5. Build ---
    - name: Build
      shell: bash
      run: cmake --build --preset ci_${{ inputs.compiler }}_af_${{ inputs.backend }}

    # --- 6. Save BuildCache ---
    - name: Save BuildCache
      if: always()
      uses: ./.github/actions/save-cache
      with:
        path: .buildcache
        key: ${{ steps.buildcache.outputs.primary-key }}

        global-tag: buildcache-${{ inputs.cache_prefix }}-${{ inputs.compiler }}-${{ inputs.backend }}
        gh-token: ${{ github.token }}