name: "Install Flashlight Core Dependencies"
description: "Install backend and autograd backend dependencies for the Flashlight Core"
inputs:
  backend:
    required: true
    description: "Tensor backend to install"
  autograd_backend:
    required: false
    description: "Autograd backend backend to install"
  distributed_backend:
    required: false
    description: "Distributed backend dependencies to install."

runs:
  using: "composite"
  steps:
    # ]----- Backend dependencies
    # ArrayFire
    - name: Cache ArrayFire (Windows)
      id: cache-arrayfire-windows
      uses: actions/cache@v4
      if: runner.os == 'Windows' && inputs.backend == 'ArrayFire'
      with:
        path: C:\tools\ArrayFire
        key: arrayfire-windows-3.10.0
    
    - name: "Install ArrayFire (Windows)"
      if: runner.os == 'Windows' && inputs.backend == 'ArrayFire' && steps.cache-arrayfire-windows.outputs.cache-hit != 'true'
      run: |
        choco install --no-progress wget -y
        cd $HOME
        wget --quiet https://arrayfire.gateway.scarf.sh/windows/3.10.0/ArrayFire.exe -O ArrayFire.exe
        7z.exe x ArrayFire.exe -o"C:\tools\ArrayFire" -y
        rm ArrayFire.exe
      shell: bash -el {0}

    - name: Set ArrayFire Env (Windows)
      if: runner.os == 'Windows' && inputs.backend == 'ArrayFire'
      run: |
        echo "ArrayFire_DIR=C:\tools\ArrayFire" >> $GITHUB_ENV
        echo "C:\tools\ArrayFire\lib" >> $GITHUB_PATH
      shell: bash -el {0}
    
    - name: "Install ArrayFire (Linux)"
      run: |
        sudo apt update
        sudo apt-key adv --fetch-key https://repo.arrayfire.com/GPG-PUB-KEY-ARRAYFIRE-2020.PUB
        echo "deb [arch=amd64] https://repo.arrayfire.com/debian all main" | sudo tee /etc/apt/sources.list.d/arrayfire.list
        sudo apt update
        sudo apt install arrayfire-cmake=3.8.1-2 arrayfire-headers=3.8.1-2 arrayfire-cpu3-mkl=3.8.1-2 arrayfire-cpu3-dev=3.8.1-2
      if: runner.os == 'Linux' && inputs.backend == 'ArrayFire'
      shell: bash -el {0}
    - name: "Install ArrayFire (macOS)"
      run: brew install arrayfire
      if: runner.os == 'macOS' && inputs.backend == 'ArrayFire'
      shell: bash -el {0}
    # oneDNN
    - name: Install oneDNN with micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: flashlight
        create-args: onednn -c conda-forge
      if: (inputs.backend == 'oneDNN' || inputs.autograd_backend == 'oneDNN')
    # MPI
    - name: "Install OpenMPI (Linux)"
      run: |
        sudo apt update
        sudo apt install -y openmpi-bin libopenmpi-dev
      if: runner.os == 'Linux' && inputs.distributed_backend != '' && inputs.distributed_backend != 'Stub'
      shell: bash -el {0}
