name: 'Save Cache'
description: 'Saves to GitHub Cache (Always) and GHCR (Only on master)'
inputs:
  path:
    description: 'File path to save'
    required: true
  key:
    description: 'Key used in the restore step'
    required: true
  global-tag:
    description: 'OCI Tag for GHCR (e.g. vcpkg-linux-gcc-latest)'
    required: true
  gh-token:
    description: 'GitHub Token for GHCR auth'
    required: true
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    # --- Local github cache ---
    - name: Save Local Cache
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.path }}
        key: ${{ inputs.key }}

    # --- Global GHCR cache (master only) ---
    - name: Save Global Cache
      if: github.ref == 'refs/heads/master'
      shell: bash
      env:
        REPO: ghcr.io/${{ github.repository }}
        TAG: master-${{ inputs.global-tag }}
        TARGET_PATH: ${{ inputs.path }}
      run: |
        if [ -d "$TARGET_PATH" ]; then
          echo "Compressing for Global Cache..."
          tar -czf cache-archive.tar.gz "$TARGET_PATH"
          
          echo "Pushing to GHCR..."
          oras push "$REPO/cache:$TAG" cache-archive.tar.gz
          rm cache-archive.tar.gz
        fi