name: 'Core Build'
description: 'Handles Caching, Configuration, and Compilation'
inputs:
  configure_preset:
    description: 'CMake preset used for configuration'
    required: true
  build_preset:
    description: 'CMake preset used for building'
    required: true
  cache_key_prefix:
    description: 'Unique string to separate caches (e.g. linux-gcc-cpu)'
    required: true

runs:
  using: "composite"
  steps:
    # --- 1. Restore Vcpkg ---
    - name: Restore vcpkg cache
      id: restore-vcpkg
      uses: actions/cache/restore@v4
      with:
        path: vcpkg_installed
        key: vcpkg-${{ inputs.cache_key_prefix }}-${{ hashFiles('vcpkg.json') }}
        restore-keys: vcpkg-${{ inputs.cache_key_prefix }}-


    # --- 2. Configure ---
    - name: Configure CMake
      shell: bash
      run: |
        [ -f ci/CMakeUserPresets.json ] && cp ci/CMakeUserPresets.json CMakeUserPresets.json
        cmake --preset ${{ inputs.configure_preset }}

    # --- 3. Save Vcpkg ---
    - name: Save vcpkg cache
      if: steps.restore-vcpkg.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: vcpkg_installed
        key: ${{ steps.restore-vcpkg.outputs.cache-primary-key }}

    # --- 4. Restore BuildCache ---
    - name: Restore BuildCache
      id: restore-buildcache
      uses: actions/cache/restore@v4
      with:
        path: .buildcache
        key: buildcache-${{ inputs.cache_key_prefix }}-${{ github.run_id }}
        restore-keys: buildcache-${{ inputs.cache_key_prefix }}-

    # --- 5. Build ---
    - name: Build
      shell: bash
      run: cmake --build --preset ${{ inputs.build_preset }}

    # --- 6. Save BuildCache ---
    - name: Save BuildCache
      if: always() && steps.restore-buildcache.outputs.cache-primary-key != ''
      uses: actions/cache/save@v4
      with:
        path: .buildcache
        key: ${{ steps.restore-buildcache.outputs.cache-primary-key }}